[project]
name = "mesh-tools"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "manifold3d>=3.5.4",
    "matplotlib>=3.11.2",
    "networkx>=3.7",
    "numpy>=2.5.3",
    "pymeshlab>=2025.7.post1",
    "rtree>=1.4.1",
    "scipy>=1.18.1",
    "shapely>=2.1.2",
    "triangle>=20250106",
    "trimesh>=5.1.1",
]
